#
# Module manifest for module 'LabMod'
#
# Generated by: Jon Ormond
#
# Generated on: 12/31/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'LabMod.psm1'

# Version number of this module.
# https://msdn.microsoft.com/en-us/library/system.version(v=vs.110).aspx Remarks section
ModuleVersion = '1.5.0.0'

# ID used to uniquely identify this module
GUID = '60052e85-08ba-4495-bd55-f8d3ef1339ff'

# Author of this module
Author = 'Jon Ormond'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = '(c) 2026 Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell module for Pathfinder Lab on-prem VM management'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '7.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = @(
    'Build-LabBaseVHDX',
    'Build-LabBaseVM',
    'Copy-ToUbuntu',
    'Get-LabECX',
    'New-LabECX',
    'Start-LabVmRequest',
    'New-LabVM',
    'Remove-LabECX',
    'Remove-LabVM',
    'Uninstall-LabMod',
    'Update-LabLibrary',
    'Update-LabMod'
)

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

